const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js')
    .js('resources/js/autosize.js', 'public/js')
    .js('resources/js/banner.js', 'public/js')
    .js('resources/js/scroll.js', 'public/js')
    .js('resources/js/service.js', 'public/js')
    .js('resources/js/examples.js', 'public/js')
    .sass('resources/css/main.sass', 'public/css', [])
    .sass('resources/css/cards.sass', 'public/css', [])
    .sass('resources/css/variables.sass', 'public/css', [])
    .sass('resources/css/footer.sass', 'public/css', [])
    .sass('resources/css/map.sass', 'public/css', [])
    .sass('resources/css/navbar.sass', 'public/css', [])
    .sass('resources/css/pricelist.sass', 'public/css', [])
